# permissions for end users to view trackingservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trackingserver-viewer-role
rules:
- apiGroups:
  - ml.mlflow.org
  resources:
  - trackingservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.mlflow.org
  resources:
  - trackingservers/status
  verbs:
  - get
