apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mlflow
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: mlflow.example.ca
    http:
      paths:
      - backend:
          serviceName: mlflow
          servicePort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mlflow
  labels:
    app.kubernetes.io/name: mlflow
spec:
  host: "*.mlflow.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: "DISABLE"
---
apiVersion: ml.mlflow.org/v1alpha1
kind: TrackingServer
metadata:
  name: mlflow
spec:
  image: "mlflow"
  imagePullSecret: "registry-connection"
  replicas: 1
  size: "20Gi"
  storageClass: "managed-premium"
---
apiVersion: security.cloud.ibm.com/v1
kind: OidcConfig
metadata:
  name: mlflow
spec:
  clientId: clientid
  clientSecretRef:
    key: client-secret
    name: mlflow
  discoveryUrl: discoveryurl
  scopes: null
---
apiVersion: security.cloud.ibm.com/v1
kind: Policy
metadata:
  name: mlflow
spec:
  targets:
  - paths:
    - method: ALL
      policies:
      - config: mlflow
        policyType: oidc
        redirectUri: https://mlflow.example.ca
        rules:
        - claim: groups
          match: ANY
          source: id_token
          values:
          - group_admin
          - group_alt
      prefix: /
    serviceName: mlflow
