# ----------------------------------------------------
# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: mlflow

# Adds namespace to all resources.
namePrefix: mlflow-standard-tenant-1-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: mlflow-standard-tenant-1

# Each entry in this list should resolve to a directory
# containing a kustomization file, else the
# customization fails.
#
# The entry could be a relative path pointing to a local directory
# or a url pointing to a directory in a remote repo.
# The url should follow hashicorp/go-getter URL format
# https://github.com/hashicorp/go-getter#url-format
#
# The presence of this field means this file (the file
# you a reading) is an _overlay_ that further
# customizes information coming from these _bases_.
#
# Typical use case: a dev, staging and production
# environment that are mostly identical but differing
# crucial ways (image tags, a few server arguments,
# etc. that differ from the common base).
bases:
- ../../base

# Each entry in this list results in the creation of
# one Secret resource (it's a generator of n secrets).
secretGenerator:
- name: mlflow
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.
  env: secret.txt
  type: Opaque

# Each entry in this list should resolve to
# a kubernetes object and a JSON patch that will be applied
# to the object.
# The JSON patch is documented at https://tools.ietf.org/html/rfc6902
#
# target field points to a kubernetes object within the same kustomization
# by the object's group, version, kind, name and namespace.
# path field is a relative file path of a JSON patch file.
# The content in this patch file can be either in JSON format as
#
#  [
#    {"op": "add", "path": "/some/new/path", "value": "value"},
#    {"op": "replace", "path": "/some/existing/path", "value": "new value"}
#  ]
#
# or in YAML format as
#
# - op: add
#   path: /some/new/path
#   value: value
# - op:replace
#   path: /some/existing/path
#   value: new value
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: mlflow
  path: patch-ing.yaml
- target:
    group: security.cloud.ibm.com
    version: v1
    kind: OidcConfig
    name: mlflow
  path: patch-oidc.yaml
- target:
    group: security.cloud.ibm.com
    version: v1
    kind: Policy
    name: mlflow
  path: patch-policy.yaml
- target:
    group: ml.mlflow.org
    version: v1alpha1
    kind: TrackingServer
    name: mlflow
  path: patch-trackingserver.yaml

# generatorOptions modify behavior of all ConfigMap and Secret generators
generatorOptions:
  disableNameSuffixHash: true
