- op: replace
  path: /spec/clientId
  value: XXXXX-XXXXX-XXXXX
- op: replace
  path: /spec/clientSecretRef/name
  value: mlflow
- op: replace
  path: /spec/discoveryUrl
  value: https://mlflow.example.ca
