# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# https://github.com/Azure/actions-workflow-samples/tree/master/Kubernetes
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace:
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).
name: release
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: k8scc01covidacr
  CLUSTER_NAME: k8s-cancentral-02-covid-aks
  CLUSTER_RESOURCE_GROUP: k8s-cancentral-01-covid-aks
  STORAGE_ACCOUNT_NAME: k8scovid
  NAMESPACE: web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Connect to Azure Container registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Container build and push to a Azure Container registry (ACR)
    - run: |
        docker build -f Dockerfile -t ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator:${{ github.sha }} .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator:${{ github.sha }}

    # Scan image for vulnerabilities
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator:${{ github.sha }}
        severity-threshold: CRITICAL
        run-quality-checks: false

    # Run Kustomize
    - name: kustomize
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -k config/crd
      env:
        MLFLOW_OPERATOR_IMAGE: ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator
        MLFLOW_OPERATOR_IMAGE_VERSION: ${{ github.sha }}

    # Run Kustomize
    - name: kustomize
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -k config/default
      env:
        MLFLOW_OPERATOR_IMAGE: ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator
        MLFLOW_OPERATOR_IMAGE_VERSION: ${{ github.sha }}

    # Run Kustomize
    - name: kustomize
      uses: statcan/actions/kubectl@master
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: apply -k .
      env:
        MLFLOW_OPERATOR_IMAGE: ${{ env.REGISTRY_NAME }}.azurecr.io/mlflow-operator
        MLFLOW_OPERATOR_IMAGE_VERSION: ${{ github.sha }}
        MLFLOW_IMAGE: ${{ secrets.MLFLOW_IMAGE }}
        MLFLOW_IMAGEPULLSECRET: ${{ secrets.MLFLOW_IMAGEPULLSECRET }}
        MLFLOW_OIDC_CLIENT: ${{ secrets.MLFLOW_OIDC_CLIENT }}
        MLFLOW_OIDC_SECRET: ${{ secrets.MLFLOW_OIDC_SECRET }}
        MLFLOW_OIDC_DISCOVERY: ${{ secrets.MLFLOW_OIDC_DISCOVERY }}
        MLFLOW_ADMIN_POLICY_GROUP: ${{ secrets.MLFLOW_ADMIN_POLICY_GROUP }}
        DAAAS_TENANT1_DOMAIN_NAME: ${{ secrets.DAAAS_TENANT1_DOMAIN_NAME }}
        DAAAS_TENANT1_PREFIX: ${{ secrets.DAAAS_TENANT1_PREFIX }}
        DAAAS_TENANT1_POLICY_GROUP: ${{ secrets.DAAAS_TENANT1_POLICY_GROUP }}
